import type { LottieHandle } from "lottie-react";
import { LottieSvg } from "lottie-react";
import { useEffect, useRef } from "react";
import { aiRobo, aiRoboTransitions } from "@/shared/assets";

export type Emotion = "happy" | "sad" | "thinking" | "idle" | "listening" | "speaking";

const STATE_SEGMENTS: Record<Emotion, [number, number]> = {
  idle: [0, 29],
  happy: [391, 479],
  sad: [106, 180],
  listening: [31, 105],
  thinking: [271, 390],
  speaking: [181, 270],
};

// Bridge segments generated by tools/build-mascot-transitions.mjs; keyed
// "from>to". Playing [bridge, target] tweens the pose across the state change
// (the player loops only the last range, i.e. the target gesture).
const TRANSITIONS = aiRoboTransitions as unknown as Record<string, [number, number]>;

export function LottieMascot({ emotion }: { emotion: Emotion }) {
  const lottieRef = useRef<LottieHandle>(null);
  // Captured once so the `segment` prop shows the initial pose without a flash
  // and never re-drives the player on change — transitions go through the effect.
  const initialSegment = useRef(STATE_SEGMENTS[emotion]);
  const prevEmotion = useRef(emotion);

  useEffect(() => {
    if (prevEmotion.current === emotion) return; // initial pose handled by `segment`
    const handle = lottieRef.current;
    const from = prevEmotion.current;
    prevEmotion.current = emotion;
    if (!handle) return;

    const target = STATE_SEGMENTS[emotion];
    const bridge = TRANSITIONS[`${from}>${emotion}`];
    if (bridge) handle.playSegments([bridge, target]);
    else handle.playSegments(target);
  }, [emotion]);

  return (
    <LottieSvg
      src={aiRobo}
      loop
      autoplay
      segment={initialSegment.current}
      lottieRef={lottieRef}
      className="h-full w-full"
      role="presentation"
    />
  );
}
