/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Decks */
        get: operations["list_decks_decks_get"];
        put?: never;
        /** Create Deck */
        post: operations["create_deck_decks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deck Cards */
        get: operations["list_deck_cards_decks__deck_id__cards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Words */
        post: operations["import_words_decks__deck_id__import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Queue */
        get: operations["review_queue_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Review */
        post: operations["record_review_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Sentence */
        post: operations["check_sentence_practice_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice/example": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Practice Example */
        get: operations["practice_example_practice_example_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice/topic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Practice Topic */
        get: operations["practice_topic_practice_topic_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice/hint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Practice Hint */
        get: operations["practice_hint_practice_hint_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice/drill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Practice Drill */
        post: operations["practice_drill_practice_drill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Practice Translate */
        get: operations["practice_translate_practice_translate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice/interview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Practice Interview */
        post: operations["practice_interview_practice_interview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/curriculum": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Curriculum Map */
        get: operations["curriculum_map_curriculum_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/curriculum/modules/{module_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Module Detail */
        get: operations["module_detail_curriculum_modules__module_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/curriculum/lessons/{module_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lesson */
        get: operations["lesson_curriculum_lessons__module_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/curriculum/lessons/{module_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Lesson Read */
        post: operations["mark_lesson_read_curriculum_lessons__module_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CardOut */
        CardOut: {
            /** Id */
            id: number | null;
            /** Word */
            word: string;
            /** Translation */
            translation: string;
            /** Transcription */
            transcription: string | null;
            /** Section */
            section?: string | null;
        };
        /** CheckSentenceIn */
        CheckSentenceIn: {
            /** Card Id */
            card_id: number;
            /** Sentence */
            sentence: string;
        };
        /** CreateDeckIn */
        CreateDeckIn: {
            /** Name */
            name: string;
        };
        /** CurriculumLessonMetaOut */
        CurriculumLessonMetaOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Level */
            level: string;
            /** Track */
            track: string;
            /** Estimated Minutes */
            estimated_minutes: number;
            /** Objectives */
            objectives: string[];
            /** Skills */
            skills: string[];
            /** References */
            references: components["schemas"]["CurriculumReferenceOut"][];
        };
        /** CurriculumLessonOut */
        CurriculumLessonOut: {
            /** Markdown */
            markdown: string;
            meta: components["schemas"]["CurriculumLessonMetaOut"];
        };
        /** CurriculumLevelOut */
        CurriculumLevelOut: {
            /** Level */
            level: string;
            /** Modules */
            modules: components["schemas"]["CurriculumModuleOut"][];
        };
        /** CurriculumMapOut */
        CurriculumMapOut: {
            /** Levels */
            levels: components["schemas"]["CurriculumLevelOut"][];
            /** Recommended Module Id */
            recommended_module_id?: string | null;
        };
        /** CurriculumModuleDetailOut */
        CurriculumModuleDetailOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Level */
            level: string;
            /** Track */
            track: string;
            /** Status */
            status: string;
            /** Objectives */
            objectives: string[];
            /** References */
            references: components["schemas"]["CurriculumReferenceOut"][];
            /** Has Quiz */
            has_quiz: boolean;
            /** Estimated Minutes */
            estimated_minutes: number;
            /** Quiz Best Score */
            quiz_best_score?: number | null;
        };
        /** CurriculumModuleOut */
        CurriculumModuleOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Level */
            level: string;
            /** Track */
            track: string;
            /** Availability */
            availability: string;
            /** Status */
            status: string;
            /** Quiz Best Score */
            quiz_best_score?: number | null;
        };
        /** CurriculumModuleProgressOut */
        CurriculumModuleProgressOut: {
            /** Module Id */
            module_id: string;
            /** Status */
            status: string;
            /** Lesson Read At */
            lesson_read_at?: string | null;
            /** Quiz Best Score */
            quiz_best_score?: number | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /** CurriculumReferenceOut */
        CurriculumReferenceOut: {
            /** Book */
            book: string;
            /** Locator */
            locator: string;
        };
        /** DeckOut */
        DeckOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** DrillIn */
        DrillIn: {
            /** Card Id */
            card_id: number;
            /** Message */
            message: string;
        };
        /** DrillOut */
        DrillOut: {
            /** Response */
            response: string;
            /** Question */
            question?: string | null;
        };
        /** ExampleOut */
        ExampleOut: {
            /** Example */
            example: string;
        };
        /** FeedbackOut */
        FeedbackOut: {
            verdict: components["schemas"]["Verdict"];
            /** Feedback */
            feedback: string;
            /** Corrected */
            corrected: string | null;
            /** Example */
            example: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportIn */
        ImportIn: {
            /** Raw */
            raw: string;
            /**
             * Format
             * @enum {string}
             */
            format: "csv" | "markdown";
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
        };
        /** ImportOut */
        ImportOut: {
            /** Committed */
            committed: boolean;
            /** Imported */
            imported: components["schemas"]["CardOut"][];
            /** Errors */
            errors: components["schemas"]["RowErrorOut"][];
        };
        /** InterviewIn */
        InterviewIn: {
            /** Topic */
            topic: string;
            /**
             * Lang
             * @default en
             * @enum {string}
             */
            lang: "ru" | "en";
            /**
             * Difficulty
             * @default middle
             * @enum {string}
             */
            difficulty: "junior" | "middle" | "senior";
            /**
             * Mode
             * @default auto
             * @enum {string}
             */
            mode: "auto" | "next" | "random";
            /**
             * Used Question Ids
             * @default []
             */
            used_question_ids: number[];
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["InterviewMessage"][];
        };
        /** InterviewMessage */
        InterviewMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "interviewer";
            /** Content */
            content: string;
        };
        /** InterviewOut */
        InterviewOut: {
            verdict?: components["schemas"]["Verdict"] | null;
            /** Feedback */
            feedback?: string | null;
            /** Corrected */
            corrected?: string | null;
            /** Question */
            question: string;
            /** Question Id */
            question_id?: number | null;
        };
        /** ReviewIn */
        ReviewIn: {
            /** Card Id */
            card_id: number;
            /**
             * Rating
             * @enum {integer}
             */
            rating: 1 | 2 | 3 | 4;
        };
        /** RowErrorOut */
        RowErrorOut: {
            /** Line */
            line: number;
            /** Reason */
            reason: string;
        };
        /** SentenceTranslation */
        SentenceTranslation: {
            /** Full */
            full: string;
            /**
             * Words
             * @default []
             */
            words: components["schemas"]["WordTranslation"][];
        };
        /** StatsOut */
        StatsOut: {
            /** Due Today */
            due_today: number;
            /** Total Reviews */
            total_reviews: number;
            /**
             * Streak
             * @default 0
             */
            streak: number;
            /**
             * Fsrs New
             * @default 0
             */
            fsrs_new: number;
            /**
             * Fsrs Learning
             * @default 0
             */
            fsrs_learning: number;
            /**
             * Fsrs Review
             * @default 0
             */
            fsrs_review: number;
            /**
             * Fsrs Relearning
             * @default 0
             */
            fsrs_relearning: number;
            /**
             * Activity
             * @default []
             */
            activity: {
                [key: string]: number | string;
            }[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Verdict
         * @enum {string}
         */
        Verdict: "ok" | "needs_work";
        /** WordHintOut */
        WordHintOut: {
            /** Meaning */
            meaning: string;
            /** Example */
            example?: string | null;
        };
        /** WordTranslation */
        WordTranslation: {
            /** Word */
            word: string;
            /** Translation */
            translation: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_decks_decks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckOut"][];
                };
            };
        };
    };
    create_deck_decks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeckIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deck_cards_decks__deck_id__cards_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                section?: string | null;
            };
            header?: never;
            path: {
                deck_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_words_decks__deck_id__import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_queue_review_queue_get: {
        parameters: {
            query: {
                deck_id: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_review_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_stats_get: {
        parameters: {
            query: {
                deck_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_sentence_practice_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckSentenceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    practice_example_practice_example_get: {
        parameters: {
            query: {
                card_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExampleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    practice_topic_practice_topic_get: {
        parameters: {
            query: {
                deck_id: number;
                topic: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    practice_hint_practice_hint_get: {
        parameters: {
            query: {
                card_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordHintOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    practice_drill_practice_drill_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DrillIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrillOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    practice_translate_practice_translate_get: {
        parameters: {
            query: {
                text: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentenceTranslation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    practice_interview_practice_interview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    curriculum_map_curriculum_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurriculumMapOut"];
                };
            };
        };
    };
    module_detail_curriculum_modules__module_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurriculumModuleDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lesson_curriculum_lessons__module_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurriculumLessonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_lesson_read_curriculum_lessons__module_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurriculumModuleProgressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
