from datetime import datetime
from typing import Protocol

from vocab_api.domain.curriculum.progress import LearnerProfile, ModuleProgress
from vocab_api.domain.curriculum.skill_item import SkillItem


class LearnerProfileRepository(Protocol):
    async def get(self) -> LearnerProfile: ...
    async def save(self, profile: LearnerProfile) -> None: ...


class ModuleProgressRepository(Protocol):
    async def get(self, module_id: str) -> ModuleProgress: ...
    async def save(self, progress: ModuleProgress) -> None: ...
    async def list(self) -> list[ModuleProgress]: ...
    async def mark_lesson_read(self, module_id: str, now: datetime) -> ModuleProgress: ...
    async def mark_quiz_attempted(
        self, module_id: str, best_score: float, now: datetime
    ) -> ModuleProgress: ...


class QuizAttemptRepository(Protocol):
    """Append-only log of individual quiz answers (used by review in Phase 2)."""

    async def record(
        self,
        module_id: str,
        item_id: str,
        given: str,
        correct: bool,
        answered_at: datetime,
    ) -> None: ...


class SkillItemRepository(Protocol):
    """Spaced-repetition units for micro-skills (Phase 2)."""

    async def by_skill(self, skill: str) -> SkillItem | None: ...
    async def get(self, skill_item_id: int) -> SkillItem: ...
    async def add(self, item: SkillItem) -> SkillItem: ...
    async def save(self, item: SkillItem) -> None: ...
    async def due(self, now: datetime, limit: int) -> list[SkillItem]: ...
    async def leeches(self, limit: int) -> list[SkillItem]: ...