from datetime import datetime
from typing import Protocol

from vocab_api.domain.curriculum.progress import LearnerProfile, ModuleProgress


class LearnerProfileRepository(Protocol):
    async def get(self) -> LearnerProfile: ...
    async def save(self, profile: LearnerProfile) -> None: ...


class ModuleProgressRepository(Protocol):
    async def get(self, module_id: str) -> ModuleProgress: ...
    async def save(self, progress: ModuleProgress) -> None: ...
    async def list(self) -> list[ModuleProgress]: ...
    async def mark_lesson_read(self, module_id: str, now: datetime) -> ModuleProgress: ...