from typing import Protocol

from vocab_api.domain.practice.feedback import Feedback
from vocab_api.domain.practice.interview import InterviewEvaluation
from vocab_api.domain.practice.word_hint import WordHint


class LlmProvider(Protocol):
    async def check_sentence(self, word: str, sentence: str) -> Feedback: ...
    async def suggest_example(self, word: str) -> str: ...
    async def select_topic_words(self, topic: str, limit: int) -> list[str]: ...
    async def describe_word(self, word: str) -> WordHint: ...
    async def drill_word(self, word: str, user_message: str) -> tuple[str, str]: ...
    async def translate_sentence(self, text: str) -> tuple[str, list[dict[str, str]]]: ...
    async def interview(
        self,
        topic: str,
        lang: str,
        difficulty: str,
        messages: list[dict[str, str]],
    ) -> InterviewEvaluation: ...
