from datetime import datetime
from typing import Protocol

from vocab_api.domain.card.card import Card
from vocab_api.domain.deck.deck import Deck
from vocab_api.domain.practice.sentence_attempt import SentenceAttempt
from vocab_api.domain.review.review_log import ReviewLogEntry


class DeckRepository(Protocol):
    async def add(self, deck: Deck) -> Deck: ...
    async def get(self, deck_id: int) -> Deck: ...
    async def list(self) -> list[Deck]: ...


class CardRepository(Protocol):
    async def add_many(self, cards: list[Card]) -> list[Card]: ...
    async def get(self, card_id: int) -> Card: ...
    async def save(self, card: Card) -> None: ...
    async def due(self, deck_id: int, now: datetime) -> list[Card]:
        """All genuinely due cards (Learning/Review/Relearning) with due <= now."""
    async def new_cards(self, deck_id: int, limit: int) -> list[Card]:
        """Brand-new cards (state New) in creation/id order, at most limit."""
    async def count_due(self, deck_id: int, now: datetime) -> int:
        """Genuinely due count, excluding brand-new cards."""
    async def count_new(self, deck_id: int) -> int:
        """Brand-new (state New) cards in the deck."""
    async def count_introduced_today(self, deck_id: int, start_of_day: datetime) -> int:
        """Cards whose first review (introduced_at) is on/after start_of_day."""
    async def list_all(
        self, deck_id: int, limit: int, offset: int, section: str | None
    ) -> list[Card]: ...
    async def by_words(self, deck_id: int, words: list[str]) -> list[Card]: ...
    async def count_by_state(self, deck_id: int) -> dict[str, int]: ...
    async def soonest_due(self, deck_id: int, now: datetime) -> datetime | None:
        """Earliest future due in the deck (excludes overdue and New); None if none."""


class ReviewLogRepository(Protocol):
    async def add(self, entry: ReviewLogEntry) -> None: ...
    async def count_reviews(self, deck_id: int) -> int: ...
    async def count_reviews_on(self, deck_id: int, day_start: datetime) -> int: ...
    async def streak(self, deck_id: int) -> int: ...
    async def activity(self, deck_id: int, days: int) -> list[dict[str, int | str]]: ...
    async def most_recent(self, limit: int) -> list[int]:
        """Card ids of the most recent reviews across all decks, newest first."""


class SentenceAttemptRepository(Protocol):
    async def add(self, attempt: SentenceAttempt) -> SentenceAttempt: ...
    async def list_for_card(self, card_id: int) -> list[SentenceAttempt]: ...
