from datetime import datetime
from typing import Protocol

from vocab_api.domain.card.card import Card
from vocab_api.domain.deck.deck import Deck
from vocab_api.domain.practice.sentence_attempt import SentenceAttempt
from vocab_api.domain.review.review_log import ReviewLogEntry


class DeckRepository(Protocol):
    async def add(self, deck: Deck) -> Deck: ...
    async def get(self, deck_id: int) -> Deck: ...
    async def list(self) -> list[Deck]: ...


class CardRepository(Protocol):
    async def add_many(self, cards: list[Card]) -> list[Card]: ...
    async def get(self, card_id: int) -> Card: ...
    async def save(self, card: Card) -> None: ...
    async def due(self, deck_id: int, now: datetime, limit: int) -> list[Card]: ...
    async def count_due(self, deck_id: int, now: datetime) -> int: ...
    async def list_all(
        self, deck_id: int, limit: int, offset: int, section: str | None
    ) -> list[Card]: ...
    async def by_words(self, deck_id: int, words: list[str]) -> list[Card]: ...
    async def count_by_state(self, deck_id: int) -> dict[str, int]: ...


class ReviewLogRepository(Protocol):
    async def add(self, entry: ReviewLogEntry) -> None: ...
    async def count_reviews(self, deck_id: int) -> int: ...
    async def streak(self, deck_id: int) -> int: ...
    async def activity(self, deck_id: int, days: int) -> list[dict[str, int | str]]: ...
    async def most_recent(self, limit: int) -> list[int]:
        """Card ids of the most recent reviews across all decks, newest first."""


class SentenceAttemptRepository(Protocol):
    async def add(self, attempt: SentenceAttempt) -> SentenceAttempt: ...
    async def list_for_card(self, card_id: int) -> list[SentenceAttempt]: ...
