from datetime import datetime
from typing import Protocol

from vocab_api.domain.card.card import Card
from vocab_api.domain.deck.deck import Deck
from vocab_api.domain.review.review_log import ReviewLogEntry


class DeckRepository(Protocol):
    async def add(self, deck: Deck) -> Deck: ...
    async def get(self, deck_id: int) -> Deck: ...
    async def list(self) -> list[Deck]: ...


class CardRepository(Protocol):
    async def add_many(self, cards: list[Card]) -> list[Card]: ...
    async def get(self, card_id: int) -> Card: ...
    async def save(self, card: Card) -> None: ...
    async def due(self, deck_id: int, now: datetime, limit: int) -> list[Card]: ...
    async def count_due(self, deck_id: int, now: datetime) -> int: ...


class ReviewLogRepository(Protocol):
    async def add(self, entry: ReviewLogEntry) -> None: ...
    async def count_reviews(self, deck_id: int) -> int: ...
